QuanLyGPLX-LapTrinhWeb/Areas/Admin/Controllers/HoSoController.cs
using PagedList;
using QuanLyGPLX_LapTrinhWeb.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using QuanLyGPLX_LapTrinhWeb.App_Start;

namespace QuanLyGPLX_LapTrinhWeb.Areas.Admin.Controllers
{
    public class HoSoController : Controller
    {
        // GET: Admin/HoSo
        MyDataDataContext data = new MyDataDataContext();

        #region danh sách hồ sơ
        /*---------Danh sách hồ sơ---------*/
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult DanhSachHoSo(int? page, string search)
        {
            if (page == null)
                page = 1;
            int pageSize = 5;
            int pageNum = page ?? 1;
            if (search == null)
            {
                var all_HoSo = (from hs in data.HoSoGPLXes
                                join ll in data.LyLiches on hs.SoCCCD equals ll.SoCCCD
                                join px in data.PhuongXas on ll.DiaChi equals px.MaPX
                                join qh in data.QuanHuyens on px.MaHuyen equals qh.MaHuyen
                                join t in data.TinhTPs on qh.MaTinh equals t.MaTinh
                                orderby ll.Ten, ll.HoLot ascending
                                select new HoSo
                                {
                                    MaGPLX = hs.MaGPLX,
                                    HoTen = ll.HoLot + " " + ll.Ten,
                                    NgaySinh = String.Format("{0:dd/MM/yyyy}", ll.NgaySinh),
                                    GioiTinh = ll.GioiTinh,
                                    DiaChi = px.TenPX + ", " + qh.TenHuyen + ", " + t.TenTinh,
                                    NgayCap = String.Format("{0:dd/MM/yyyy}", hs.NgayCapGPLX),
                                    NgayHetHan = String.Format("{0:dd/MM/yyyy}", hs.NgayHetHanGPLX),
                                    HangGPLX = hs.MaHang
                                });
                return View(all_HoSo.ToPagedList(pageNum, pageSize));
            }
            else
            {
                var all_HoSo = (from hs in data.HoSoGPLXes
                                join ll in data.LyLiches on hs.SoCCCD equals ll.SoCCCD
                                join px in data.PhuongXas on ll.DiaChi equals px.MaPX
                                join qh in data.QuanHuyens on px.MaHuyen equals qh.MaHuyen
                                join t in data.TinhTPs on qh.MaTinh equals t.MaTinh
                                orderby ll.Ten, ll.HoLot ascending
                                where hs.MaGPLX.Contains(search)
                                select new HoSo
                                {
                                    MaGPLX = hs.MaGPLX,
                                    HoTen = ll.HoLot + " " + ll.Ten,
                                    NgaySinh = String.Format("{0:dd/MM/yyyy}", ll.NgaySinh),
                                    GioiTinh = ll.GioiTinh,
                                    DiaChi = px.TenPX + ", " + qh.TenHuyen + ", " + t.TenTinh,
                                    NgayCap = String.Format("{0:dd/MM/yyyy}", hs.NgayCapGPLX),
                                    NgayHetHan = String.Format("{0:dd/MM/yyyy}", hs.NgayHetHanGPLX),
                                    HangGPLX = hs.MaHang
                                });
                if (all_HoSo.Count() == 0)
                {
                    ViewBag.DanhSachHoSo = "Không tìm thấy hồ sơ nào!";
                }
                return View(all_HoSo.ToPagedList(pageNum, pageSize));
            }
        }
        #endregion

        #region chi tiết hồ sơ
        /*---------Chi tiết hồ sơ---------*/
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Details(string id)
        {
            var D_HoSo = (from hs in data.HoSoGPLXes
                          join ll in data.LyLiches on hs.SoCCCD equals ll.SoCCCD
                          join px in data.PhuongXas on ll.DiaChi equals px.MaPX
                          join qh in data.QuanHuyens on px.MaHuyen equals qh.MaHuyen
                          join t in data.TinhTPs on qh.MaTinh equals t.MaTinh
                          join dt in data.DanTocs on ll.MaDT equals dt.MaDT
                          join qt in data.QuocTiches on ll.MaQT equals qt.MaQT
                          join ttsh in data.TrungTamSatHaches on hs.MaTT equals ttsh.MaTT
                          where hs.MaGPLX == id
                          select new HoSo
                          {
                              HinhAnh = hs.HinhAnh,
                              MaGPLX = hs.MaGPLX,
                              HoTen = ll.HoLot + " " + ll.Ten,
                              NgaySinh = String.Format("{0:dd/MM/yyyy}", ll.NgaySinh),
                              GioiTinh = ll.GioiTinh,
                              SDT = ll.SDT,
                              DanToc = dt.TenDT,
                              DiaChi = px.TenPX + ", " + qh.TenHuyen + ", " + t.TenTinh,
                              QuocTich = qt.TenQT,
                              NgayCap = String.Format("{0:dd/MM/yyyy}", hs.NgayCapGPLX),
                              NgayHetHan = String.Format("{0:dd/MM/yyyy}", hs.NgayHetHanGPLX),
                              HangGPLX = hs.MaHang,
                              DiemLT = hs.DiemLT.ToString(),
                              DiemTH = hs.DiemTH.ToString(),
                              TTSH = ttsh.TenTT
                          }).First();
            return View(D_HoSo);
        }
        #endregion

        #region chỉnh sửa hồ sơ
        /*---------Chỉnh sửa hồ sơ---------*/
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Edit(string id)
        {
            var Hang = data.HangGPLXes.Select(p => p.MaHang).ToList();
            ViewBag.HangGPLX = new SelectList(Hang, "TenHang");

            var TenTTSH = data.TrungTamSatHaches.Select(p => new { p.MaTT, p.TenTT }).ToList();
            ViewBag.TenTTSH = new SelectList(TenTTSH, "MaTT", "TenTT", data.HoSoGPLXes.Where(p => p.MaGPLX == id).Select(p => p.MaTT).First());

            var E_MaGPLX = data.HoSoGPLXes.First(m => m.MaGPLX == id);
            var E_NgayCap = data.HoSoGPLXes.First(m => m.MaGPLX == id);
            ViewBag.NgayCap = String.Format("{0:MM/dd/yyyy}", E_NgayCap.NgayCapGPLX);

            var E_NgayHetHan = data.HoSoGPLXes.First(m => m.MaGPLX == id);
            ViewBag.NgayHetHan = String.Format("{0:MM/dd/yyyy}", E_NgayHetHan.NgayHetHanGPLX);
            return View(E_MaGPLX);
        }

        [AdminAuthorize(idChucNang = 1)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, FormCollection collection)
        {
            var E_GPLX = data.HoSoGPLXes.SingleOrDefault(m => m.MaGPLX == id);
            var E_MaHang = collection["MaHang"];
            var E_HinhAnh = collection["HinhAnh"];
            var E_NgayCap = collection["NgayCapGPLX"];
            var E_NgayHetHan = collection["NgayHetHanGPLX"];
            var E_DiemLT = collection["DiemLT"];
            var E_DiemTH = collection["DiemTH"];
            var E_MaTTSH = collection["TenTT"];
            if (E_GPLX == null)
            {
                ViewData["Error"] = "Don't empty";
            }
            else
            {
                E_GPLX.MaHang = E_MaHang;
                E_GPLX.HinhAnh = E_HinhAnh;
                E_GPLX.NgayCapGPLX = DateTime.ParseExact(E_NgayCap, "MM/dd/yyyy", null);
                E_GPLX.NgayHetHanGPLX = DateTime.ParseExact(E_NgayHetHan, "MM/dd/yyyy", null);
                E_GPLX.DiemLT = int.Parse(E_DiemLT);
                E_GPLX.DiemTH = int.Parse(E_DiemTH);
                E_GPLX.MaTT = E_MaTTSH;
                TryUpdateModel(E_GPLX);
                data.SubmitChanges();
                return RedirectToAction("DanhSachHoSo");
            }
            return this.Edit(id);
        }
        #endregion

        #region xóa hồ sơ
        /*---------Xóa hồ sơ---------*/
        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Delete(string id)
        {
            var D_MaGPLX = data.HoSoGPLXes.First(m => m.MaGPLX == id);
            return View(D_MaGPLX);
        }

        [AdminAuthorize(idChucNang = 1)]
        [HttpPost]
        public ActionResult Delete(string id, FormCollection collection)
        {
            var D_MaGPLX = data.HoSoGPLXes.First(m => m.MaGPLX == id);
            data.HoSoGPLXes.DeleteOnSubmit(D_MaGPLX);
            data.SubmitChanges();
            return RedirectToAction("DanhSachHoSo");
        }

        [AdminAuthorize(idChucNang = 1)]
        [HttpPost]
        public ActionResult DeleteHoSo(string id)
        {
            var MaGPLX = data.HoSoGPLXes.Where(a => a.MaGPLX == id).FirstOrDefault();
            data.HoSoGPLXes.DeleteOnSubmit(MaGPLX);
            data.SubmitChanges();
            return Json(new { status = "Success" });
        }
        #endregion

        #region thêm hồ sơ
        /*---------Thêm mới hồ sơ---------*/
        [AdminAuthorize(idChucNang = 1)]
        [HttpPost]
        public JsonResult GetSoCCCD(string Prefix)
        {
            var SoCCCD = (from CCCD in data.LyLiches
                          where CCCD.SoCCCD.StartsWith(Prefix)
                          select new
                          {
                              CCCD.SoCCCD
                          }).ToList();
            return Json(SoCCCD, JsonRequestBehavior.AllowGet);
        }

        [AdminAuthorize(idChucNang = 1)]
        public ActionResult Create()
        {
            var Hang = data.HangGPLXes.Select(p => p.MaHang).ToList();
            ViewBag.HangGPLX = new SelectList(Hang, "TenHang");

            var TenTTSH = data.TrungTamSatHaches.Select(p => p.TenTT).ToList();
            ViewBag.TenTTSH = new SelectList(TenTTSH, "TenTT");

            return View();

QuanLyGPLX-LapTrinhWeb/Areas/Admin/Controllers/TrungTamSatHachController.cs
using PagedList;
using QuanLyGPLX_LapTrinhWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyGPLX_LapTrinhWeb.Areas.Admin.Controllers
{
    public class TrungTamSatHachController : Controller
    {
        // GET: Admin/TrungTamSatHach
        MyDataDataContext data = new MyDataDataContext();

        #region danh sách trung tâm sát hạch
        public ActionResult DanhSachTrungTam(int? page, string search)
        {
            if (page == null)
                page = 1;
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            if (search == null)
            {
                var dstt = data.TrungTamSatHaches.ToList();
                return View(dstt.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                var dstt = data.TrungTamSatHaches.Where(t => t.MaTT.Contains(search) || t.TenTT.Contains(search)).ToList();
                if (dstt.Count == 0)
                    ViewBag.ThongBao = "Không tìm thấy trung tâm sát hạch nào";
                return View(dstt.ToPagedList(pageNumber, pageSize));
            }
        }
        #endregion

        #region chỉnh sửa trung tâm sát hạch
        public ActionResult Edit(string id)
        {
            var tt = data.TrungTamSatHaches.First(t => t.MaTT == id);
            return View(tt);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string id, FormCollection collection)
        {
            var E_TTSH = data.TrungTamSatHaches.SingleOrDefault(m => m.MaTT == id);
            var E_TenTT = collection["TenTT"];
            if (E_TTSH == null)
            {
                ViewData["Error"] = "Don't empty";
            }
            else
            {
                E_TTSH.TenTT = E_TenTT;
                TryUpdateModel(E_TTSH);
                data.SubmitChanges();
                return RedirectToAction("DanhSachTrungTam");
            }
            return this.Edit(id);
        }
        #endregion

        #region xóa trung tâm sát hạch
        public ActionResult DeleteTrungTam(string id)
        {
            var MaTT = data.TrungTamSatHaches.Where(a => a.MaTT == id).FirstOrDefault();
            data.TrungTamSatHaches.DeleteOnSubmit(MaTT);
            data.SubmitChanges();
            return Json(new { status = "Success" });
        }
        #endregion

        #region thêm trung tâm sát hạch
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection collection)
        {
            var C_MaTT = collection["MaTT"];
            var C_TenTT = collection["TenTT"];
            if (C_MaTT == null || C_TenTT == null)
            {
                ViewData["Error"] = "Don't empty";
            }
            else
            {
                TrungTamSatHach ttsh = new TrungTamSatHach();
                ttsh.MaTT = C_MaTT;
                ttsh.TenTT = C_TenTT;
                data.TrungTamSatHaches.InsertOnSubmit(ttsh);
                data.SubmitChanges();
                return RedirectToAction("DanhSachTrungTam");
            }
            return this.Create();
        }
        #endregion
    }
}

QuanLyGPLX-LapTrinhWeb/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
    <title>@ViewBag.Title - Trang quản lý giấy phép lái xe</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Content/style.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <style>
        label.error {
            color: red;
        }
    </style>
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="border-end bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading border-bottom bg-light" style="height:58px">
                <i class="fa-solid fa-car"></i>
                Quản lý GPLX
            </div>
            @*hiển thị session*@
            <div class="list-group list-group-flush">

                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/Home/Index" )">
                    <i class="fa-solid fa-house"></i>
                    Trang chủ
                </a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("DanhSachHoSo", "HoSo")">
                    <i class="fa-solid fa-table-list"></i>
                    Danh sách hồ sơ
                </a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("DanhSachTrungTam", "TrungTamSatHach")">
                    <i class="fa-solid fa-table"></i>
                    Danh sách TTSH
                </a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="/Home/Logout">
                    <i class="fa-solid fa-right-to-bracket"></i>
                    Đăng xuất
                </a>
            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom" style="height:58px">
                <div class="container-fluid">
                    <button class="btn btn-outline" id="sidebarToggle">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div style=" display: flex; justify-content: end;">
                        <i class="fa-solid fa-user" style="padding:4px"></i>
                        Xin chào
                        <strong style="padding-left:4px">@Session["nameUser"]</strong>
                        !!
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <div class="container body-content">
                @RenderBody()
            </div>
        </div>
    </div>

    <script>
        window.addEventListener('DOMContentLoaded', event => {
            const sidebarToggle = document.body.querySelector('#sidebarToggle');
            if (sidebarToggle) {
                sidebarToggle.addEventListener('click', event => {
                    event.preventDefault();
                    document.body.classList.toggle('sb-sidenav-toggled');
                    localStorage.setItem('sb|sidebar-toggle', document.body.classList.contains('sb-sidenav-toggled'));
                });
            }

        });
    </script>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="https://code.jquery.com/jquery-3.6.4.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    @RenderSection("edit", required: false)
    @RenderSection("create", required: false)
    @RenderSection("danhsach", required: false)
</body>
</html>

QuanLyGPLX-LapTrinhWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
    <title>Trang chủ - Trang tra cứu giấy phép lái xe</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Content/sub.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark" style="background-color: #202878;">
            <div class="container">
                @Html.ActionLink("Hệ thống GPLX", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>@Html.ActionLink("Hồ sơ", "DanhSachHoSo", "Admin/HoSo", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Đăng nhập", "Login", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>
                </div>
            </div>
        </nav>*@
    <div id="module-1" class="header">
        <div class="container">
            <div id="module-2" class="logo">
                <a href="@Url.Action("Index", "Home")" title="Trang chủ">
                    <img class=" logo-banner" src="~/Content/images/logo.png" alt="Logo">
                </a>
            </div>
            <div id="module-3" class="navigation">
                <ul class="nav">
                    <li>@Html.ActionLink("Trang chủ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    @if (Session["username"] != null)
                    {
                        <li>@Html.ActionLink("Hồ sơ", "DanhSachHoSo", "Admin/HoSo", new { area = "" }, new { @class = "nav-link" })</li>
                        <li style="float:right;width:180px" class="dropdown">
                            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false" style="transform: translateX(-20px);">
                                <i class="fas fa-user"></i>
                                @Session["nameUser"]
                            </a>
                            <ul class="dropdown-menu" style="color:red">
                                <li><a class="dropdown-item" href="@Url.Action("Logout", "Home")" style="color: black;">Đăng xuất</a></li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li style="float:right">@Html.ActionLink("Đăng nhập", "Login", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    <br />
    <footer class="footer-distributed">

        <div class="footer-left">

            <h3>Hệ thống quản lý GPLX <i class="fa-solid fa-traffic-light"></i></h3><hr />
            <p class="footer-project-about">
                <span>Về hệ thống</span>
                Hệ thống cho phép người dùng tra cứu và xem tin tức về tin tức giao thông
            </p>

            <div class="footer-icons">
                <a href="https://www.facebook.com/ptt27092002" target="_blank"><i class="fa-brands fa-square-facebook"></i></a>
                <a href="https://github.com/minhhieuphamit/QuanLyGPLX-LapTrinhWeb" target="_blank"><i class="fa-brands fa-square-github"></i></a>
            </div>

        </div>

        <div class="footer-center">
            <div>
                <i class="fa fa-phone"></i>
                <a style="text-decoration: none; color: #ffffff; "> 0706068259 | 0785924515</a>
            </div>

            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="mailto:minhhieupham@gmail.com">minhhieupham2002@gmail.com</a></p>
            </div>
            <div>
                <i class="fa fa-map-marker"></i>
                <p>
                    <span>
                        <a href="https://goo.gl/maps/Ls7Fa6RjD4qvoKhQ9">Thủ Đức Campus Hutech Khu E</a>
                    </span>
                </p>
            </div>
            <br />
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d979.6052124401169!2d106.78458809852604!3d10.855560627276397!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3175276e7ea103df%3A0xb6cf10bb7d719327!2sThu%20Duc%20Campus%20Hutech%20khu%20E!5e0!3m2!1svi!2s!4v1679802192657!5m2!1svi!2s" width="300" height="200" style="border:0; margin-left:30px" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>

        <div class="footer-right">

        </div>

    </footer>

    <script src="https://code.jquery.com/jquery-3.6.4.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    @RenderSection("tracuu", required: false)
</body>
</html>